name: Deploy to QAS

on:
  push:
    branches:
      - qas

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/D-care
            git fetch origin
            git checkout qas
            git pull origin qas
            sudo docker compose down
            sudo docker compose build --no-cache
            sudo docker compose up -d
